# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 815)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
                                         "    background-color: rgb(255, 255, 255);\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_left = QtWidgets.QWidget(self.centralwidget)
        self.widget_left.setMinimumSize(QtCore.QSize(130, 0))
        self.widget_left.setMaximumSize(QtCore.QSize(130, 16777215))
        self.widget_left.setStyleSheet("#widget_left {\n"
                                       "    border-right: 10px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                       "}")
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout_5.setContentsMargins(0, 16, 10, 0)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_monitor_title = QtWidgets.QLabel(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_monitor_title.sizePolicy().hasHeightForWidth())
        self.label_monitor_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.label_monitor_title.setFont(font)
        self.label_monitor_title.setStyleSheet("#label_monitor_title {\n"
                                               "    margin-left: 1px\n"
                                               "}")
        self.label_monitor_title.setObjectName("label_monitor_title")
        self.verticalLayout_5.addWidget(self.label_monitor_title)
        self.widget_building = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_building.sizePolicy().hasHeightForWidth())
        self.widget_building.setSizePolicy(sizePolicy)
        self.widget_building.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_building.setStyleSheet("#widget_building {\n"
                                           "    background-color: rgba(255, 255, 255, 0);\n"
                                           "    border-style: solid;\n"
                                           "}\n"
                                           "\n"
                                           "#widget_building:checked {\n"
                                           "    border-left-width: 5px;\n"
                                           "    border-left-color: rgb(25, 185, 231);\n"
                                           "}")
        self.widget_building.setCheckable(True)
        self.widget_building.setChecked(True)
        self.widget_building.setAutoExclusive(True)
        self.widget_building.setObjectName("widget_building")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_building)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_building_ic = QtWidgets.QLabel(self.widget_building)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_building_ic.sizePolicy().hasHeightForWidth())
        self.label_building_ic.setSizePolicy(sizePolicy)
        self.label_building_ic.setMinimumSize(QtCore.QSize(40, 40))
        self.label_building_ic.setMaximumSize(QtCore.QSize(40, 40))
        self.label_building_ic.setText("")
        self.label_building_ic.setPixmap(QtGui.QPixmap(":/main/building.png"))
        self.label_building_ic.setScaledContents(True)
        self.label_building_ic.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label_building_ic.setObjectName("label_building_ic")
        self.verticalLayout.addWidget(self.label_building_ic, 0, QtCore.Qt.AlignHCenter)
        self.label_building = QtWidgets.QLabel(self.widget_building)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_building.setFont(font)
        self.label_building.setObjectName("label_building")
        self.verticalLayout.addWidget(self.label_building, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.widget_building)
        self.widget_status = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_status.sizePolicy().hasHeightForWidth())
        self.widget_status.setSizePolicy(sizePolicy)
        self.widget_status.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_status.setStyleSheet("#widget_status {\n"
                                         "    background-color: rgba(255, 255, 255, 0);\n"
                                         "    border-style: solid\n"
                                         "}\n"
                                         "#widget_status:checked {\n"
                                         "    border-left-width: 5px;\n"
                                         "    border-left-color: rgb(25, 185, 231);\n"
                                         "}")
        self.widget_status.setCheckable(True)
        self.widget_status.setAutoExclusive(True)
        self.widget_status.setObjectName("widget_status")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_status)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_status_ic = QtWidgets.QLabel(self.widget_status)
        self.label_status_ic.setMinimumSize(QtCore.QSize(40, 40))
        self.label_status_ic.setMaximumSize(QtCore.QSize(40, 40))
        self.label_status_ic.setText("")
        self.label_status_ic.setPixmap(QtGui.QPixmap(":/main/status.png"))
        self.label_status_ic.setScaledContents(True)
        self.label_status_ic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_ic.setObjectName("label_status_ic")
        self.verticalLayout_2.addWidget(self.label_status_ic, 0, QtCore.Qt.AlignHCenter)
        self.label_status = QtWidgets.QLabel(self.widget_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_status.setFont(font)
        self.label_status.setScaledContents(False)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_2.addWidget(self.label_status, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.widget_status)
        self.widget_abnormal = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_abnormal.sizePolicy().hasHeightForWidth())
        self.widget_abnormal.setSizePolicy(sizePolicy)
        self.widget_abnormal.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_abnormal.setStyleSheet("#widget_abnormal {\n"
                                           "    background-color: rgba(255, 255, 255, 0);\n"
                                           "    border-style: solid;\n"
                                           "}\n"
                                           "#widget_abnormal:checked {\n"
                                           "    border-left-width: 5px;\n"
                                           "    border-left-color: rgb(25, 185, 231);\n"
                                           "}")
        self.widget_abnormal.setCheckable(True)
        self.widget_abnormal.setAutoExclusive(True)
        self.widget_abnormal.setObjectName("widget_abnormal")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_abnormal)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_abnormal_ic = QtWidgets.QLabel(self.widget_abnormal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_abnormal_ic.sizePolicy().hasHeightForWidth())
        self.label_abnormal_ic.setSizePolicy(sizePolicy)
        self.label_abnormal_ic.setMinimumSize(QtCore.QSize(40, 40))
        self.label_abnormal_ic.setMaximumSize(QtCore.QSize(40, 40))
        self.label_abnormal_ic.setText("")
        self.label_abnormal_ic.setPixmap(QtGui.QPixmap(":/main/abnormal.png"))
        self.label_abnormal_ic.setScaledContents(True)
        self.label_abnormal_ic.setObjectName("label_abnormal_ic")
        self.verticalLayout_3.addWidget(self.label_abnormal_ic, 0, QtCore.Qt.AlignHCenter)
        self.label_abnormal = QtWidgets.QLabel(self.widget_abnormal)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_abnormal.setFont(font)
        self.label_abnormal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_abnormal.setObjectName("label_abnormal")
        self.verticalLayout_3.addWidget(self.label_abnormal, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.widget_abnormal)
        self.line = QtWidgets.QFrame(self.widget_left)
        self.line.setMinimumSize(QtCore.QSize(0, 40))
        self.line.setStyleSheet("#line {\n"
                                "    margin-top: 40px\n"
                                "}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.label_record_title = QtWidgets.QLabel(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_record_title.sizePolicy().hasHeightForWidth())
        self.label_record_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.label_record_title.setFont(font)
        self.label_record_title.setStyleSheet("#label_record_title {\n"
                                              "    margin-left: 1px\n"
                                              "}")
        self.label_record_title.setObjectName("label_record_title")
        self.verticalLayout_5.addWidget(self.label_record_title)
        self.widget_record = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_record.sizePolicy().hasHeightForWidth())
        self.widget_record.setSizePolicy(sizePolicy)
        self.widget_record.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_record.setStyleSheet("#widget_record {\n"
                                         "    background-color: rgba(255, 255, 255, 0);\n"
                                         "}")
        self.widget_record.setCheckable(True)
        self.widget_record.setAutoExclusive(True)
        self.widget_record.setObjectName("widget_record")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_record)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_record_ic = QtWidgets.QLabel(self.widget_record)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_record_ic.sizePolicy().hasHeightForWidth())
        self.label_record_ic.setSizePolicy(sizePolicy)
        self.label_record_ic.setMinimumSize(QtCore.QSize(40, 40))
        self.label_record_ic.setMaximumSize(QtCore.QSize(40, 40))
        self.label_record_ic.setText("")
        self.label_record_ic.setPixmap(QtGui.QPixmap(":/main/record.png"))
        self.label_record_ic.setScaledContents(True)
        self.label_record_ic.setObjectName("label_record_ic")
        self.verticalLayout_4.addWidget(self.label_record_ic, 0, QtCore.Qt.AlignHCenter)
        self.label_record = QtWidgets.QLabel(self.widget_record)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_record.sizePolicy().hasHeightForWidth())
        self.label_record.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_record.setFont(font)
        self.label_record.setAlignment(QtCore.Qt.AlignCenter)
        self.label_record.setObjectName("label_record")
        self.verticalLayout_4.addWidget(self.label_record)
        self.verticalLayout_5.addWidget(self.widget_record)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget_left)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_class = QtWidgets.QWidget()
        self.page_class.setObjectName("page_class")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_class)
        self.verticalLayout_7.setContentsMargins(10, -1, 10, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget.addWidget(self.page_class)
        self.page_reocrd = QtWidgets.QWidget()
        self.page_reocrd.setObjectName("page_reocrd")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_reocrd)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.stackedWidget.addWidget(self.page_reocrd)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智慧课堂实时监测系统"))
        self.label_monitor_title.setText(_translate("MainWindow",
                                                    "<html><head/><body><p><span style=\" font-weight:600;\">实时监控</span></p></body></html>"))
        self.label_building.setText(_translate("MainWindow", "教学楼"))
        self.label_status.setText(_translate("MainWindow", "状态"))
        self.label_abnormal.setText(_translate("MainWindow", "异常"))
        self.label_record_title.setText(_translate("MainWindow",
                                                   "<html><head/><body><p><span style=\" font-weight:600;\">历史记录</span></p></body></html>"))
        self.label_record.setText(_translate("MainWindow", "记录"))


import resource.main_rc
